### ISSUE TITLE
Using kubernetes service breaks something

### ISSUE THREAD

**Issue by loic-lopez** [thephpleague/flysystem#1002]
### Bug Report

Got `ftp_fput(): Illegal PORT command.`when using a kubernetes service with PASV disabled on the ftp server.

|    Q        |   A
|------------ | ------
| BC Break    | don't know
| Version     | shipped with laravel 5.7.24

#### Summary

So i'm trying to connect my ftp server hosted by a Kubernetes Cluster so i did this config:
```yml
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: exosuite-vsftpd
  labels:
    app: exosuite-vsftpd
spec:
  type: ClusterIP
  ports:
    - port: 20
      name: vsftpd-data
    - port: 21
      name: vsftpd-control
  selector:
    app: exosuite-vsftpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
        - name: vsftpd
          image: fauria/vsftpd
          ports:
            - containerPort: 20
              name: ftp-data
            - containerPort: 21
              name: ftp-server
          env:
            - name: FTP_USER
              value: "user"
            - name: FTP_PASS
              value: "root"
            - name: PASV_ENABLE
              value: NO
            - name: LOG_STDOUT
              value: "log"
```

So i have tried to create a Pod config:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: staging
  name: vsftpd
spec:
  containers:
    - name: vsftpd
      image: fauria/vsftpd
      ports:
        - containerPort: 20
          hostPort: 20
          name: ftp-data
        - containerPort: 21
          hostPort: 21
          name: ftp-server
      env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "root"
        - name: PASV_ENABLE
          value: "NO"
        - name: LOG_STDOUT
          value: "log"
```

And with the Pod everything is working properly.

#### How to reproduce

Create a Kubernetes Service for a ftp server.
