### ISSUE TITLE
S3 - Set storage class for bucket files

### ISSUE THREAD

**Issue by bastien70** [thephpleague/flysystem#1478]
### Question

Hello, I use flysystem to send my files on S3, especially with Scaleway : https://flysystem.thephpleague.com/v1/docs/adapter/scaleway-object-storage/

There are 3 classes for files :  STANDARD, ONEZONE_IA, GLACIER

This represents how the file should be stored.

After speaking with Scaleway support, they told me that I could choose the class by specifying the "x-amz-storage-class" header to each file sent, but it's work for API only.

Using flysystem, I've in my **services.yaml** 

```yaml
    Aws\S3\S3Client:
        arguments:
            -   version: '2006-03-01'
                region: "%env(AWS_S3_REGION)%"
                endpoint: 'https://s3.fr-par.scw.cloud'
                credentials:
                    key: "%env(AWS_S3_ACCESS_ID)%"
                    secret: "%env(AWS_S3_ACCESS_SECRET)%"
```

And in my **flysystem.yaml**

```yaml
flysystem:
    storages:
        uploads_adapter:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
```
Is there a way to specify the class from the config file?

According https://www.scaleway.com/en/docs/storage/object/api-cli/object-operations/ 

```
Note: To define the [storage class](https://www.scaleway.com/en/docs/storage/object/concepts/#storage-class) of the object directly upon creation, use the --storage-class <class> option with awscli or add the x-amz-storage-class: <class> header when using the S3 API. You can specify one of the following classes: STANDARD, ONEZONE_IA, GLACIER. Example: x-amz-storage-class: ONEZONE_IA. If no class is specified, the object is created as STANDARD by default.
```

I tried something like this : 

```yaml
flysystem:
    storages:
        uploads_adapter:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                options:
                    storage-class: 'ONEZONE_IA'
```

But no effect

EDIT : Ok I found the solution ! Just use "StorageClass" option instead of "storage-class", like this : 

```yaml
flysystem:
    storages:
        uploads_adapter:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                options:
                    StorageClass: 'ONEZONE_IA'
```
