### ISSUE TITLE
How to set the endpoint for s3-compatible adapter

### ISSUE THREAD

**Issue by tacman** [thephpleague/flysystem#1839]
I've answered my question, posting it in case it's useful for someone else.

```
S3_ENDPOINT=https://nyc3.digitaloceanspaces.com
```

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                streamReads: true
                prefix: '%env(S3_STORAGE_PREFIX)%'
```

Or maybe it belongs in the s3 service?

```yaml
services:
    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: 'nyc3'
              endpoint: '%env(S3_ENDPOINT)%'
              credentials:
                  key: '%env(AWS_S3_ACCESS_ID)%'
                  secret: '%env(AWS_S3_ACCESS_SECRET)%'
```
