### ISSUE TITLE
Is flysystem-aws-s3-v3 compatible with Minio?

### ISSUE THREAD

**Issue by filisko** [thephpleague/flysystem#1866]
Hi, THANKS for this amazing work guys!

I just have a question, is https://github.com/thephpleague/flysystem-aws-s3-v3 compatible with Minio?

Thanks!

**Comment by Vegeeto** [comment]
Yes! It supports it! I use it from version 1.

**Comment by SimonMellerin** [comment]
Hi @filisko did you succeed to connect to a MinIo instance ?

Do you have an example ? I'd like to see what arguments you gave to the `AwsS3Client` constructor.

Thanks
Simon

**Comment by SimonMellerin** [comment]
Found an example here : https://yoandev.co/lobject-storage-dans-une-application-symfony#mettre-en-place-lutilisation-de-lobject-storage-dans-notre-application


```
Aws\\S3\\S3Client:
        arguments:
            - version: 'latest'
              region: 'eu-east-1'
              endpoint: '127.0.0.1:9000'
              credentials:
                key: 'access1234'
                secret: 'secret1234'
```
