### ISSUE TITLE
Impossible to create the root directory "".

### ISSUE THREAD

**Issue by andrey-helldar** [thephpleague/flysystem#878]
env: Laravel 5.5
parent os: Windows 10 Pro. Simlink is created on the OS command line.
sites environment: Homestead based on Ubuntu 16.04 with php 7.2.

I have a symlink `storage/app/private` >> `e:\_sites\helpers_storage_private\`.

When I try to write a file, I get an error:

```bash
In Local.php line 106:
Impossible to create the root directory "".
```

```php
$filename = 'my-file.txt';
$content = 'foo bar';
\Storage::disk('private')->put($filename, $content);
```

If you change the selected disk to a public drive, the file is successfully written.

The public disk folder is not a symlink.

My `filesystems.php` configuration file:
```php
'disks' => [
    'public' => [
        'driver'     => 'local',
        'root'       => storage_path('app/public'),
        'url'        => env('APP_URL') . '/storage',
        'visibility' => 'public',
    ],

    'private' => [
        'driver'     => 'local',
        'root'       => storage_path('app/private'),
        'visibility' => 'private',
    ],
]
```

**Comment by frankdejonge** [comment]
Hi @andrey-helldar, could you run the following script and paste back the output:

```php
<?php 
$root = "your/root/path/here";
var_dump($root);
var_dump(is_dir($root));
var_dump(is_link($root));
var_dump(is_file($root));
```

**Comment by andrey-helldar** [comment]
Code:
```php
$root = __DIR__ . "/../storage/app/private";
echo '<pre>';
var_dump([
	'root' => $root,
	'is_dir' => is_dir($root),
	'is_link' => is_link($root),
	'is_file' => is_file($root),
]);
echo '</pre>';
```

Result:
```
array(4) {
  ["root"]=> string(69) "/home/vagrant/code/helpers.company.dev/routes/../storage/app/private"
  ["is_dir"]=> bool(false)
  ["is_link"]=> bool(true)
  ["is_file"]=> bool(false)
}
```

Next:
```php
$root = __DIR__ . "/../storage/app/private/1.txt";
var_dump(file_exists($root));
// result: bool(false)
```
![2017-12-28 23-55-50 work pc 192 168 0 208 - remote desktop connection manager v2 7](https://user-images.githubusercontent.com/10347617/34423085-d14373f4-ec2a-11e7-9d17-431ccd768022.png)

My homestead config:
```yaml
---
ip: "192.168.10.10"
memory: 2048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/pub

keys:
    - ~/.ssh/private.ppk

folders:
    - map: c:/OpenServer/domains
      to: /home/vagrant/code

sites:
    - map: helpers.company.dev
      to: /home/vagrant/code/helpers.company.dev/public
      schedule: true

databases:
    - helpers
```

**Comment by andrey-helldar** [comment]
Maybe the problem is that the symlink leads to a folder that is outside the Homestead environment?

Inside Homestead, I created a symlink to a folder in the same project:
`helpers.company.dev/public/storage` >> `helpers.company.dev/storage/app/public`.

Code:
```php
$root = __DIR__ . "/../public/storage";
echo '<pre>';
var_dump([
	'root' => $root,
	'is_dir' => is_dir($root),
	'is_link' => is_link($root),
	'is_file' => is_file($root),
]);
echo '</pre>';
```

And result:
```bash
array(4) {
  ["root"]=>string(64) "/home/vagrant/code/helpers.company.dev/routes/../public/storage"
  ["is_dir"]=>bool(true)
  ["is_link"]=>bool(true)
  ["is_file"]=>bool(false)
}
```

And check file:
```php
$root = __DIR__ . "/../public/storage/1.txt";
echo '<pre>';
var_dump([
	'root' => $root,
	'is_dir' => is_dir($root),
	'is_link' => is_link($root),
	'is_file' => is_file($root),
]);
echo '</pre>';
```

Result:
```bash
array(4) {
  ["root"]=>string(70) "/home/vagrant/code/helpers.company.dev/routes/../public/storage/1.txt"
  ["is_dir"]=>bool(false)
  ["is_link"]=>bool(false)
  ["is_file"]=>bool(true)
}
```

**Comment by frankdejonge** [comment]
That must be it, must be something in homestead, but it's still strange. It's def not something fixable in Flysystem, but I encourage you to find out what and why this happens so we can document it and help other people who are having similar issues.

**Comment by andrey-helldar** [comment]
So, the problem was the compatibility of the Windows parent operating system and the Linux operating system running inside the VirtualBox virtual machine (Vagrant, Homestead).

**Comment by andrey-helldar** [comment]
I closed the issue, because the problem was in the operating system.

**Comment by frankdejonge** [comment]
👍

**Comment by andrey-helldar** [comment]
I inform you that I successfully solved my problem 🙂

In the Homestead settings:
**before:**
```yaml
folders:
    - map: c:/OpenServer/domains
      to: /home/vagrant/code
```

**after:**
```yaml
folders:
    - map: c:/OpenServer/domains
      to: /home/vagrant/code

    - map: e:/_sites/storage_private
      to: /home/vagrant/code/helpers.company.dev/storage/private
```

Next, in windows deleted all the created symlinks.

Then inside the virtual machine created new ones.

For convenience, I wrote commands for creating symlinks in the `after.sh` file.

Perhaps this issue will be read by people with a similar problem. Let her solution be here 🙂
